language: java
jdk: oraclejdk8
services:
- docker
before_install:
- sudo service mysql stop
- docker pull takimatraining/devops-training-db
- docker run -d -p 127.0.0.1:3306:3306 takimatraining/devops-training-db
script:
- mvn verify
- |
  mvn clean install sonar:sonar \
  -Dsonar.projectKey=nkpf_sample-application-students \
  -Dsonar.organization=nkpf-github \
  -Dsonar.host.url=https://sonarcloud.io \
  -Dsonar.login=$SONAR_TOKEN
cache:
  directories:
  - "$HOME/.m2/repository"
env:
  global:
    secure: OjNMB6SCTrPQOmqmz2k3N+FK52ZUD7ZPdhFxmQt0xsu219ycVSbCMeQ1jcQdU5qKkNjh4v/ijurneOhehEsjushXrL4vHkFTg56aqVbeRmBuWbXLGoeU4Y9V/rYz5Dx+JxdBjc6/sSYmFNqmzL3HhEghvtysV6wH4IVNhU4gLqUWs3t0Hgqq3vdbWQCdbAH93ayWIMxyDrg34VOAYRZcS4bXmM5RjzgOcr/xQKvWuafU+wM09Mv4JyTi5CogvIgGWLeZR8MTpsUq6cmavfN2jILCtpK4oQ8nQXxKRHd40dilZuI7MFvz/RBqiPjjauZ0D1dhqzdFB/xpUogFAsLtnPVuXouZH658gQ/tNDfngXydoanyeRvg1S9PAtN+uCkwF0yC1wDEZwhtR3BUNy+YLHA+P12IXxQpKR1bPz6I+3Q+wcXGSpIQ6Z4XUn6MOfZ2YzWypMtXiqR8AvIVREzShr85QlFrkaY0bTfF2GDAuswbOFxjg4rfVOQtgQUHqZt4BtDjVw1l0dtsR1/1Z+pFchsPf3D/ALOx5kyHTrli66NBz8gZ7Il0/4TmKRFu5m6oby00UNscO13FGIkvkX8HE7jGfS4QxsPTqDsYkPyHly6ilW/j1CO3dxhSv7RwhvStSA07/LuvZAmr210LAM/sH2HUxC/lgaV3UICDp0/hXvQ=
